server:
  port: 8180

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
      discovery:
        locator:
          enabled: true


  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin, Access-Control-Request-Method, Access-Control-Request-Headers

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000

services:
  api-gateway-service: http://localhost:8180
  account-service: http://localhost:8181
  dashboard-app: http://localhost:4200
  login-app: http://localhost:4201
