server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka-service-registry
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
  main:
    allow-bean-definition-overriding: true
